package: rex_redactor
version: '1.6.5'
author: Friends Of REDAXO
supportpage: github.com/FriendsOfREDAXO/rex_redactor

page:
    title: 'translate:title'
    perm: rex_redactor[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: rex_redactor[profiles] }