package: rex_redactor
version: '1.3.5'
author: Thomas Kaegi
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:title'
    perm: rex_redactor[]
    pjax: true
    subpages:
        tutorial: { title: 'translate:tutorial', perm: rex_redactor[tutorial] }
        profiles: { title: 'translate:profiles', perm: rex_redactor[profiles] }