package: rex_redactor
version: '1.6.4'
author: Thomas Kaegi
supportpage: github.com/phoebusryan/rex_redactor

page:
    title: 'translate:title'
    perm: rex_redactor[]
    pjax: true
    subpages:
        profiles: { title: 'translate:profiles', perm: rex_redactor[profiles] }