package: rex_redactor
version: '1.0.1'
author: Thomas Kaegi
supportpage: www.redaxo.org/de/forum/

page:
    title: 'translate:title'
    perm: rex_redactor[]
    subpages:
        tutorial: { title: 'translate:tutorial', perm: rex_redactor[tutorial] }
        configuration: { title: 'translate:configuration', perm: rex_redactor[configuration] }
        profiles: { title: 'translate:profiles', perm: rex_redactor[profiles] }
        css: { title: 'translate:css', perm: rex_redactor[css] }
        js: { title: 'translate:js', perm: rex_redactor[js] }
